import { jsPDF } from 'jspdf';
import { format } from 'date-fns';

interface Task {
    id: string;
    title: string;
    description?: string;
    status: string;
    dueAt?: string;
    category: string;
    isRecurring?: boolean;
    recurrenceInterval?: string | null;
}

export const exportTasksToPDF = (tasks: Task[], filename: string = 'my-tasks') => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('My Tasks', 20, 25);

    // Date generated
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);
    doc.text(`Generated: ${format(new Date(), 'MMM d, yyyy h:mm a')}`, 20, 35);

    let yPos = 50;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    const lineHeight = 7;

    // Group by status
    const pending = tasks.filter(t => t.status !== 'completed');
    const completed = tasks.filter(t => t.status === 'completed');

    const renderSection = (title: string, taskList: Task[]) => {
        if (taskList.length === 0) return;

        // Section header
        if (yPos > pageHeight - 40) {
            doc.addPage();
            yPos = 25;
        }

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text(`${title} (${taskList.length})`, margin, yPos);
        yPos += lineHeight * 2;

        taskList.forEach((task) => {
            // Check if we need a new page
            if (yPos > pageHeight - 30) {
                doc.addPage();
                yPos = 25;
            }

            // Task checkbox and title
            doc.setFontSize(11);
            doc.setFont('helvetica', task.status === 'completed' ? 'normal' : 'bold');
            doc.setTextColor(task.status === 'completed' ? 128 : 0, task.status === 'completed' ? 128 : 0, task.status === 'completed' ? 128 : 0);

            const checkbox = task.status === 'completed' ? '☑' : '☐';
            const taskTitle = task.title.length > 60 ? task.title.substring(0, 57) + '...' : task.title;
            doc.text(`${checkbox} ${taskTitle}`, margin, yPos);
            yPos += lineHeight;

            // Due date and category (smaller, indented)
            doc.setFontSize(9);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(100, 100, 100);

            let meta = `   ${task.category.charAt(0).toUpperCase() + task.category.slice(1)}`;
            if (task.dueAt) {
                meta += ` | Due: ${format(new Date(task.dueAt), 'MMM d, yyyy')}`;
            }
            if (task.isRecurring && task.recurrenceInterval) {
                meta += ` | Repeats: ${task.recurrenceInterval}`;
            }
            doc.text(meta, margin, yPos);
            yPos += lineHeight * 1.5;
        });

        yPos += lineHeight; // Extra space between sections
    };

    renderSection('Pending Tasks', pending);
    renderSection('Completed Tasks', completed);

    // Footer on last page
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Your Thoughts App', margin, pageHeight - 10);

    // Save
    doc.save(`${filename}.pdf`);
};
